<title>Tasaka Managara</title>
<meta charset="utf-8">
<meta http-equiv="Cache-Control" content="no-store, no-cache, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<link rel="stylesheet" type="text/css" href="<?php echo __BASE_URL?>view/asset/font/Source_Sans_Pro/stylesheet.css" >
<link rel="stylesheet" type="text/css" href="<?php echo __BASE_URL?>view/asset/font/Simple_Line_Icons/stylesheet.css" >
<link rel="stylesheet" type="text/css" href="<?php echo __BASE_URL?>view/asset/css/reset.css" >
<link rel="stylesheet" type="text/css" href="<?php echo __BASE_URL?>view/asset/css/shared.css" >
		
